# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "nuget"
    directory: "/source/"                           # Path to '*.sln' directory
    schedule:
      interval: "weekly"
    reviewers:
      - "al-kau"
    open-pull-requests-limit: 20
    groups:
      Alkau:
        patterns:
          - "Alkau.*"
      Microsoft:
        patterns:
          - "Microsoft.*"
      NUnit:
        patterns:
          - "NUnit*"

  - package-ecosystem: "github-actions"
    directory: "/"                                  # Workflow files stored in the default location
    schedule:
      interval: "monthly"
    reviewers:
      - "al-kau"
    open-pull-requests-limit: 20
    groups:
      Common-actions:
        patterns:
          - "actions/*"
      Finebits-actions:
        patterns:
          - "finebits/*"
      GitHub-actions:
        patterns:
          - "github/*"
