name: 🐞 Bug Report
title: '[BUG] <title>'
description: File a bug report
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please make sure to add as much detail as you can.

  - type: markdown
    attributes:
      value: |
        ## Description

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Describe all the steps we need to take to show the behavior that you have observed. 
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error    
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: A description of what you're experiencing. 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A description of what you expected to happen.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Environment

  - type: input
    id: app-version
    attributes:
      label: Application Version
      description: What version of the application are you using?
      placeholder: 1.0.0
    validations:
      required: true

  - type: dropdown
    id: platforms-affected
    attributes:
      label: Affected platforms
      description: Please select platforms where the issue can be reproduced. 
      multiple: true
      options:
        - Android
        - iOS
        - Linux (Desktop)
        - macOS (Desktop)
        - macOS (MacCatalyst)
        - WebAssembly
        - Windows (Desktop)
        - Windows (UWP)
        - Windows (WinUI)

    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating system
      description: What operating system version are you using?
      placeholder: Windows 11 Version 21H2 (OS Build 22000.1574)
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: "Browser Version"
      description: What version of browser are you using?
      placeholder: Microsoft Edge (Version 127.0.2651.98)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Additional information

  - type: textarea
    id: logfiles
    attributes:
      label: Log files
      description: If possible, please attach log file with log level set to debug.
      placeholder: Drag and drop your log files here!
    validations:
      required: false

  - type: textarea
    id: extrainfo
    attributes:
      label: Anything else we need to know?
      description: Anything that will give us more context about the issue!
    validations:
      required: false

 
