name: 🐞 Bug Report
title: '[BUG] <title>'
description: File a bug report
labels: ["bug", "to verify"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please make sure to add as much detail as you can.

  - type: markdown
    attributes:
      value: |
        ## Description

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        Describe all the steps we need to take to show the behavior that you have observed. 
      placeholder: |
        1. How do you create the chart.
        2. What's the chart option
        3. User interactions before the error happens.

  - type: textarea
    id: description
    attributes:
      label: Current behavior
      description: A description of what you're experiencing. You can add screenshots as well. 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A description of what you expected to happen.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Environment

  - type: input
    attributes:
      label: Version
      description: What version of the application are you running?
      placeholder: 1.0.0
    validations:
      required: true

  - type: dropdown
    id: platforms-affected
    attributes:
      label: Affected platforms
      description: Select all or any platform that you see this issue on. 
      multiple: true
      options:
        - Android
        - iOS
        - Linux (Desktop)
        - macOS (Desktop)
        - macOS (MacCatalyst)
        - WebAssembly
        - Windows (Desktop)
        - Windows (UWP)
        - Windows (WinUI)

    validations:
      required: true

  - type: markdown
    attributes:
      value: |
      
        ---

  - type: textarea
    id: logs
    attributes:
      label: Log files
      description: If possible, please attach log file with log level set to debug.
      placeholder:
        You can attach log files by clicking this area to highlight it and then
        dragging the files in.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Any additional comments?
      description: |
        e.g. some background/context of how you ran into this bug.
    validations:
      required: false

 
