name: "✍️ Create a Task"
description: Create a new task.
labels: ["Type/Task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what needs to be done.
    validations:
      required: true

  - type: textarea
    id: related
    attributes:
      label: Related Issues
      description: Mention if any related issues.
      placeholder: |
        - [ ] Sub issues 
        - [ ] Sub issues
    validations:
      required: false

  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: The items to complete to satisfy the Definition of Done.
      placeholder: |
        ```[tasklist]
        - [ ] Item 1
        - [ ] Item 2
        ```
      value: |
        ```[tasklist]
        ```
    validations:
      required: true
      render: markdown
