name: "✍️ Create a Task"
description: Create a new task.
labels: ["task"]
body:
  - type: markdown
      attributes: 
        value: |
          You are writing a task for the maintainers of this repository. If you are not a maintainer yourself, instead submit a bug report or suggestion.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what needs to be done.
    validations:
      required: true

  - type: textarea
    id: todo
    attributes:
      label: ToDo Items
      description: Complete the following items before requesting a PR review.
      placeholder: |
        - [ ] Sub issues 
        - [ ] Sub issues
    validations:
      required: false

  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Anything else we should know?
    validations:
      required: false
